### ISSUE TITLE
Directing people to use the Arch Linux forums isn't supported for derivative distros.

### ISSUE THREAD

**Issue by slithery** [swayos/swayos.github.io#14]
As above, the Arch Linux forums are only for users that have installed their system using either the Installation Guide on the wiki or the official archinstall script. Third-party installers are not supported and any users of this distro will have their threads closed and deleted.

If you release a derivative distro you are expected to provide your own support channels.

https://bbs.archlinux.org/misc.php?action=rules

Could you please remove all links to the Arch forums from your documentation.

**Comment by swayos** [comment]
I didn"t remove the link but I've modified the sentence to fit yor rules. Hope it is alright now.
BTW where did I mention "distro"? Can a distro be installed on any other unix-like systems with a setup script?

**Comment by putridpete** [comment]
Hi there! I'm not part of the Arch administration or moderation, just your Friendly Neighborhood Arch User trying to shed some light on the matter. Putting aside if SwayOS is a distro or not (or the fact that an installation ISO based on Arch is provided), I think there is a fundamental problem with the [setup-arch.sh](https://github.com/swayos/swayos.github.io/blob/main/setup-arch.sh) script. Now, just a disclaimer here: I'm no expert and I'm sure slithery or any other user more experienced than me can correct me if I'm mistaken here, but I believe that it calls for a `sudo pacman -Sy` that isn't immediately followed by a `-Su` or a `-Syu`; this is a partial upgrade and it isn't supported, [as per the wiki](https://wiki.archlinux.org/title/System_maintenance#Partial_upgrades_are_unsupported).

Leaving the user without support is only the first of two big problems, however: the other one is that this will inevitably lead to breakage. Running `pacman -Sy` is bad practice because if you try to install something after running this command, it will be newer than anything in the system. There are other scenarios that can cause a partial upgrade which can be read in the previously quoted wiki article. 

Speaking of unsupported things, the script also calls for the installation of certain AUR packages. Unfortunately, the Arch User Repository is entirely user produced and unsupported (as per the warning listed [here](https://wiki.archlinux.org/title/Arch_User_Repository)). 

This is why in Arch a manual installation and configuration is expected: in order to receive (and expedite) support, the user should be aware of how the system was installed and configured. When a third party installation tool is used or somebody else dot files/scripts are deployed, the Arch team will close any thread requesting support for it and direct users to the owners of said tools. By SwayOS not providing support for the changes it made (I think? more on that below), this essentially creates a situation where the Arch team and SwayOS would be playing hot potato with who gets to support the user, while the user hangs to dry.

Lastly (and this is just my opinion, so keep in mind I'm speaking strictly for myself and I alone here) I find that the troubleshooting section is a little vague on _what_ exactly SwayOS will support and _what_ it intends Arch to support.

**Comment by swayos** [comment]
I agree that my installer was shitty. I just removed it, moved to install script only setup.

**Comment by putridpete** [comment]
Thanks! Sorry to comment on this now closed issue, but checking the script once more I think it would be best practice to change line 25 from `sudo pacman -Su` to `sudo pacman -Syu`. You typically want to run the `-y` flag along with the `-u` one, [as the pacman documentation points out](https://archlinux.org/pacman/pacman.8.html#_sync_options_apply_to_em_s_em_a_id_so_a):

> -y, --refresh: Download a fresh copy of the master package database from the server(s) defined in [pacman.conf(5)](https://archlinux.org/pacman/pacman.conf.5.html). This should typically be used each time you use --sysupgrade or -u. [...]

When I mentioned you could use `-Su`, I meant using it right after `-Sy` which would work essentially the same as `-Syu`. Obviously `sudo pacman -Syu` would be preferable as it is shorter. Sorry if I didn't explain myself well.

**Comment by swayos** [comment]
No problem, I've modified the setup script to use -Syu, thank you!

**Comment by ayekat** [comment]
A quick look at this repo and the documentation implies SwayOS is a script that installs some software on (and otherwise reconfigures) an existing system.

Not voicing my opinion on whether this falls into the category of a custom spin/distribution/… in the context of Arch Linux, but that's also secondary given this line here:

> The installer image downloadable from swayos.github.io is arch linux based, for further help, documentation and troubleshooting please use arch linux site/forums.

This line still tells users to ask the Arch Linux community for troubleshooting help if they run into issues with what this script does to their system, so the original issue persists.

At the same time, I cannot find any downloadable "image" file, and the script seems to target different distros, so why not simply remove this?

**Comment by putridpete** [comment]
Considering the quoted text refers to a now removed installation ISO (as it happened in [this commit](https://github.com/swayos/swayos.github.io/commit/71d4dfc2a6def1fcea0957be997437e53b2ae255)), I'm guessing this was just overlooked.
