### ISSUE TITLE
Connected to wifi, but no DNS resolution

### ISSUE THREAD

**Issue by davidthewatson** [swayos/swayos.github.io#6]
I downloaded, installed, and booted into swayos today. Thanks for your amazing  work!

The only issue I've seen so far is that I can't get DNS resolution. swayos connected to my wifi router, no problem, after i entered the password on what looks like the KDE GUI config to me, and I can verify the connection from networkctl status, but resolv.conf does not get set, and indeed pings to things, fail in foot.

I looked around but I'm out of my depth on the various DNS wrapper utilities and how to inherit the DNS config from the wifi AP point at connection time. I'm guessing the various events that cause the resolve.conf to get written didn't fire.

I'd write the resolv.conf manually, but I can't find an editor since none of the usual ones are in the path. I'd also pamac update but without DNS, that seems frutless.

Thanks for your wonderful distro and help! I'm happy to grab the source and build if you have suggestions. I just need to get a little further.

**Comment by milgra** [comment]
Hi, thanks for the kind words and for the issue report! SwayOS uses systemd-resolved for DNS, my first guess would be that for some strange reason it didn't start. If it works and you have an ethernet port you should try it, if it works then the problem is with the iwd daemon, try restarting it. Actually I also have to restart the iwd service sometimes after boot ( since a full system update a month ago ), I don't know the reason yet, I will check in the arch forums.

**Comment by farseenmanekhan1232** [comment]
> I downloaded, installed, and booted into swayos today. Thanks for your amazing  work!
> 
> The only issue I've seen so far is that I can't get DNS resolution. swayos connected to my wifi router, no problem, after i entered the password on what looks like the KDE GUI config to me, and I can verify the connection from networkctl status, but resolv.conf does not get set, and indeed pings to things, fail in foot.
> 
> I looked around but I'm out of my depth on the various DNS wrapper utilities and how to inherit the DNS config from the wifi AP point at connection time. I'm guessing the various events that cause the resolve.conf to get written didn't fire.
> 
> I'd write the resolv.conf manually, but I can't find an editor since none of the usual ones are in the path. I'd also pamac update but without DNS, that seems frutless.
> 
> Thanks for your wonderful distro and help! I'm happy to grab the source and build if you have suggestions. I just need to get a little further.

Try editing mirrorlist from in /etc to fix Pacman issues , and about the DNS , even I'm facing similar issues

**Comment by swayos** [comment]
Okay, I've figured out the problem ( it appeared on my new test laptop ) : on some machine systemd-resolved doesn't work well with iwd and iwd's internal DHCP config has to be enabled. /etc/iwd/main.conf has to be created with
`[General]
EnableNetworkConfiguration=true`
The latest swayos ISO is already updated to do it automatically : https://github.com/swayos/swayos.github.io/releases/tag/202208

**Comment by lex51** [comment]
It is error on clear installation on debian.
Failure in name resolution.
All interfaces are down, up - not working.

**Comment by j-i-l** [comment]
@lex51 was facing the same situation. In my case the issue was that during the installation of debian the network interfaces did not get the predictive naming and when running the install bash script at some point the predictive names are introduced, which made the content of  `/etc/network/interfaces` useless.

The fix in my case was to simply adapt `/etc/network/interfaces` to use the predictive names.
